import { Listing } from '../types';

export const LISTINGS: Listing[] = [
  // ── Home Meals – 2769 ──────────────────────────────────────────────────────
  {
    id: 'm1',
    title: 'Homemade Biryani Night',
    description: 'Authentic Hyderabadi chicken biryani with raita and salad. Serves up to 6 people. Order by 5 pm for same-day pick-up.',
    address: '14 Ironbark Ave',
    suburb: 'Marsden Park',
    postcode: '2769',
    category: 'meals',
    latitude: -33.7220,
    longitude: 150.8390,
    price: '$18 per serve',
    date: 'Every Friday & Saturday',
    time: '6:00 PM – 8:00 PM',
    host: 'Priya S.',
    tags: ['Indian', 'Halal', 'Gluten-free option'],
  },
  {
    id: 'm2',
    title: 'Lebanese Mezze Platter',
    description: 'Fresh hummus, tabbouleh, falafel, pita and baba ganoush. Perfect for sharing. Vegetarian friendly.',
    address: '7 Banksia Dr',
    suburb: 'Stanhope Gardens',
    postcode: '2769',
    category: 'meals',
    latitude: -33.7295,
    longitude: 150.8445,
    price: '$22 per platter',
    date: 'Weekends',
    time: '12:00 PM – 3:00 PM',
    host: 'Rima K.',
    tags: ['Lebanese', 'Vegetarian', 'Halal'],
  },
  {
    id: 'm3',
    title: "Nan's Sunday Roast",
    description: 'Classic Australian Sunday roast – lamb, roast veg, gravy and Yorkshire pudding. Pre-order required.',
    address: '22 Eucalyptus Cres',
    suburb: 'Colebee',
    postcode: '2769',
    category: 'meals',
    latitude: -33.7180,
    longitude: 150.8350,
    price: '$20 per serve',
    date: 'Every Sunday',
    time: '1:00 PM – 3:00 PM',
    host: 'Margaret T.',
    tags: ['Australian', 'Family-style'],
  },
  // ── Home Meals – 2762 ──────────────────────────────────────────────────────
  {
    id: 'm4',
    title: 'Thai Street Food Box',
    description: 'Pad Thai, green curry, jasmine rice and spring rolls. Mild, medium or hot available.',
    address: '3 Railway Parade',
    suburb: 'Riverstone',
    postcode: '2762',
    category: 'meals',
    latitude: -33.6820,
    longitude: 150.8620,
    price: '$16 per box',
    date: 'Tue, Thu, Fri',
    time: '5:30 PM – 7:30 PM',
    host: 'Nong P.',
    tags: ['Thai', 'Spicy option', 'Nut-free on request'],
  },
  {
    id: 'm5',
    title: 'Filipino Fiesta Plates',
    description: 'Adobo chicken, pancit bihon, lumpia and sinangag rice. Comfort food done right.',
    address: '19 Rouse Rd',
    suburb: 'Schofields',
    postcode: '2762',
    category: 'meals',
    latitude: -33.7050,
    longitude: 150.8720,
    price: '$17 per plate',
    date: 'Weekends',
    time: '11:00 AM – 2:00 PM',
    host: 'Maria L.',
    tags: ['Filipino', 'Home-cooked'],
  },
  {
    id: 'm6',
    title: 'Vegan Bowls',
    description: 'Seasonal roasted veg, quinoa, tahini dressing and house-pickled cabbage. 100% plant-based.',
    address: '45 Hambledon Rd',
    suburb: 'Quakers Hill',
    postcode: '2762',
    category: 'meals',
    latitude: -33.7320,
    longitude: 150.8810,
    price: '$14 per bowl',
    date: 'Mon, Wed, Fri',
    time: '12:00 PM – 2:00 PM',
    host: 'Jess M.',
    tags: ['Vegan', 'Gluten-free', 'Organic'],
  },

  // ── Garage Sales – 2769 ───────────────────────────────────────────────────
  {
    id: 'g1',
    title: 'Moving-Out Mega Sale',
    description: 'Furniture, kids toys, kitchenware, books, tools and clothes. Everything must go! Cash only.',
    address: '38 Casuarina Way',
    suburb: 'Marsden Park',
    postcode: '2769',
    category: 'garage_sales',
    latitude: -33.7240,
    longitude: 150.8410,
    date: 'Sat 24 May 2026',
    time: '7:00 AM – 1:00 PM',
    tags: ['Furniture', 'Kids', 'Tools'],
  },
  {
    id: 'g2',
    title: 'Treasure Hunt Sale',
    description: 'Vintage collectibles, vinyl records, retro electronics and artwork. Bargains guaranteed.',
    address: '9 Melaleuca St',
    suburb: 'Stanhope Gardens',
    postcode: '2769',
    category: 'garage_sales',
    latitude: -33.7310,
    longitude: 150.8460,
    date: 'Sun 25 May 2026',
    time: '8:00 AM – 12:00 PM',
    tags: ['Vintage', 'Vinyl', 'Collectibles'],
  },
  {
    id: 'g3',
    title: 'Baby & Kids Clearance',
    description: "Prams, car seats, clothing 0–8 yrs, high chairs and educational toys. All items in great condition.",
    address: '55 Colebee Circuit',
    suburb: 'Colebee',
    postcode: '2769',
    category: 'garage_sales',
    latitude: -33.7165,
    longitude: 150.8330,
    date: 'Sat 31 May 2026',
    time: '8:00 AM – 11:00 AM',
    tags: ['Baby', 'Kids', 'Clothing'],
  },
  // ── Garage Sales – 2762 ───────────────────────────────────────────────────
  {
    id: 'g4',
    title: 'Backyard Blowout',
    description: 'Garden tools, outdoor furniture, BBQ, bike gear and sporting equipment.',
    address: '12 Market St',
    suburb: 'Riverstone',
    postcode: '2762',
    category: 'garage_sales',
    latitude: -33.6835,
    longitude: 150.8640,
    date: 'Sat 24 May 2026',
    time: '6:30 AM – 12:00 PM',
    tags: ['Garden', 'Outdoor', 'Sports'],
  },
  {
    id: 'g5',
    title: 'Tech & Appliance Sale',
    description: 'Laptops, monitors, kitchen appliances, smart home gadgets and cables. Everything tested and working.',
    address: '27 Piccadilly Cres',
    suburb: 'Schofields',
    postcode: '2762',
    category: 'garage_sales',
    latitude: -33.7068,
    longitude: 150.8745,
    date: 'Sun 25 May 2026',
    time: '9:00 AM – 1:00 PM',
    tags: ['Tech', 'Appliances', 'Electronics'],
  },
  {
    id: 'g6',
    title: 'Community Street Sale',
    description: "Eight houses on the street selling simultaneously. Books, clothes, homewares and more. Bring the whole family.",
    address: '4–34 Eucalypt Blvd',
    suburb: 'Quakers Hill',
    postcode: '2762',
    category: 'garage_sales',
    latitude: -33.7298,
    longitude: 150.8795,
    date: 'Sat 7 Jun 2026',
    time: '7:00 AM – 2:00 PM',
    tags: ['Street sale', 'Books', 'Homewares'],
  },

  // ── Activities – 2769 ─────────────────────────────────────────────────────
  {
    id: 'a1',
    title: 'Marsden Park Runners',
    description: 'Friendly running group for all paces. 5 km fun run every Saturday morning at Marsden Park. Beginners welcome!',
    address: 'Marsden Park Oval, Hollinsworth Rd',
    suburb: 'Marsden Park',
    postcode: '2769',
    category: 'activities',
    latitude: -33.7210,
    longitude: 150.8370,
    date: 'Every Saturday',
    time: '6:30 AM',
    tags: ['Running', 'Fitness', 'All levels'],
    contact: 'marsdenrunners@email.com',
  },
  {
    id: 'a2',
    title: 'Stanhope Cricket Club – Junior',
    description: 'Junior cricket training and weekend matches. Ages 8–16. Gear provided for first session.',
    address: 'Stanhope Village Reserve, Sentry Dr',
    suburb: 'Stanhope Gardens',
    postcode: '2769',
    category: 'activities',
    latitude: -33.7285,
    longitude: 150.8440,
    date: 'Sat & Sun',
    time: '8:00 AM – 11:00 AM',
    tags: ['Cricket', 'Junior', 'Sport'],
    contact: 'stanhopecc@cricket.nsw.au',
  },
  {
    id: 'a3',
    title: 'Yoga in the Park',
    description: 'Outdoor yoga every Sunday morning at Colebee Park. All skill levels. Bring your own mat.',
    address: 'Colebee Park, Richmond Rd',
    suburb: 'Colebee',
    postcode: '2769',
    category: 'activities',
    latitude: -33.7175,
    longitude: 150.8345,
    date: 'Every Sunday',
    time: '7:00 AM – 8:00 AM',
    tags: ['Yoga', 'Wellness', 'Outdoor'],
    contact: 'yogainthepark.cp@gmail.com',
  },
  {
    id: 'a4',
    title: 'Marsden Park Soccer (Adults)',
    description: 'Social 5-a-side soccer. Mixed teams, casual and competitive divisions. Register to join a team.',
    address: 'Marsden Park Sports Ground',
    suburb: 'Marsden Park',
    postcode: '2769',
    category: 'activities',
    latitude: -33.7228,
    longitude: 150.8395,
    date: 'Every Wednesday',
    time: '7:00 PM – 9:00 PM',
    tags: ['Soccer', 'Social', 'Adults'],
  },
  // ── Activities – 2762 ─────────────────────────────────────────────────────
  {
    id: 'a5',
    title: 'Schofields Cycling Club',
    description: 'Weekend road rides ranging from 30 km to 80 km. Helmet and road-worthy bike required. Coffee stop included.',
    address: 'Schofields Station car park',
    suburb: 'Schofields',
    postcode: '2762',
    category: 'activities',
    latitude: -33.7040,
    longitude: 150.8700,
    date: 'Every Sunday',
    time: '6:00 AM',
    tags: ['Cycling', 'Road', 'All distances'],
    contact: 'schofields.cycling@gmail.com',
  },
  {
    id: 'a6',
    title: 'Riverstone Cricket Club – Senior',
    description: 'Senior club cricket in the Blacktown competition. New players of all grades welcome. Trial sessions free.',
    address: 'Riverstone Oval, Garfield Rd',
    suburb: 'Riverstone',
    postcode: '2762',
    category: 'activities',
    latitude: -33.6810,
    longitude: 150.8610,
    date: 'Sat & Sun (season)',
    time: '9:00 AM',
    tags: ['Cricket', 'Senior', 'Competitive'],
    contact: 'riverstonecc@email.com',
  },
  {
    id: 'a7',
    title: 'Quakers Hill Bushwalking Group',
    description: 'Monthly bushwalks in the Blacktown/Hills area. Family-friendly, 5–12 km trails. Car-pool arranged from local meeting point.',
    address: 'Quakers Hill Community Centre',
    suburb: 'Quakers Hill',
    postcode: '2762',
    category: 'activities',
    latitude: -33.7335,
    longitude: 150.8825,
    date: 'First Sunday each month',
    time: '7:30 AM',
    tags: ['Bushwalking', 'Family', 'Nature'],
  },
  {
    id: 'a8',
    title: 'Kids Basketball – Schofields',
    description: 'Weekly basketball skills and drills for kids aged 6–14. Coaching by local NBL players. Limited spots.',
    address: 'The Ponds Sports Centre, Tallawong Rd',
    suburb: 'Schofields',
    postcode: '2762',
    category: 'activities',
    latitude: -33.7025,
    longitude: 150.8680,
    date: 'Every Saturday',
    time: '9:00 AM – 10:30 AM',
    tags: ['Basketball', 'Kids', 'Coaching'],
    contact: 'kidsbasketball.schofields@gmail.com',
  },
];
